version: 2.1
orbs: 
  node: circleci/node@5.1.0
jobs:
  install_node_packages:
    executor: node/default
    steps:
      - node/install-packages
workflows:
  basic_workflow:
    jobs:
      - install_node_packages